name: 'Slack Pipeline Notifications'
description: 'Send Slack notifications about your pipelines progress'
author: 'CodedSolar'
branding:
  icon: 'bell'
  color: 'purple'

inputs:
  color:
    default: ''
    description: >
      Attachment color in HEX format. By default, it's based on the "status" input
    required: false
  fields:
    default: |
      {STATUS}
      {REF}
    description: 'Fields in the multiline format. Each field must match: "<your name>: <your value>". Supported keywords: {REF}, {STATUS}'
    required: false
  ignore-failures:
    default: 'false'
    description: 'When the action exits it will be with an exit code of 0'
    required: false
  ignore-message-not-found:
    default: 'true'
    description: "When the previous message to update isn't found, a new one will be posted instead"
    required: false
  port:
    default: '3000'
    description: 'Port on which to run the Slack application'
    required: false
  port-retries:
    default: '3'
    description: 'Port retries number for an automatic bumping of unavailable ports'
    required: false
  status:
    default: 'unknown'
    description: 'Status: unknown|in-progress|success|failure|cancelled|skipped'
    required: false
  text:
    default: 'GitHub Actions {GITHUB_JOB} job in {GITHUB_REF} by {GITHUB_ACTOR}'
    description: 'Message text. Supported keywords: {GITHUB_ACTOR}, {GITHUB_JOB}, {GITHUB_REF}'
    required: false
  timestamp:
    default: ''
    description: 'Timestamp in Slack UNIX format of the previous message to update'
    required: false

outputs:
  slack-timestamp:
    description: 'Previous Slack message timestamp'

runs:
  using: 'node16'
  main: 'dist/index.js'
